# Site settings
title: Neeraj Deshmukh
description: >-
 
lang: en-US
timezone: Asia/New Delhi
image:  # This image used for Open Graph more info https://ogp.me/
repo: 
mode: light # default theme "dark" | "light"

# Profile settings
author: 
  name: Neeraj Deshmukh
  bio: I am grad student in Mathematics at IISER Pune
  username: shambhavopaya
  email: neeraj[dot]deshmukh[at]students[dot]iiserpune[dot]ac[dot]in
  avatar: /assets/img/Me.jpg

# Url settings
url: "https://shambhavopaya.github.io"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
