# Site settings
title: Neeraj Deshmukh
description: >-
 
lang: en-US
timezone: Asia/New Delhi
image:  # This image used for Open Graph more info https://ogp.me/
repo: 
mode: dark # default theme "dark" | "light"

# Profile settings
author: 
  name: Neeraj Deshmukh
  bio: I am post-doc at <a href="https://www.impan.pl/en">IMPAN</a> in the group of <a href="https://achinger.impan.pl/">Piotr Achinger</a>. Before that I was part of the working group of <a href="http://user.math.uzh.ch/ayoub/">Joseph Ayoub</a> at the University of Zurich. I was a graduate student at <a href="https://www.iiserpune.ac.in/">IISER Pune</a>; my thesis advisor was <a href="http://www.iiserpune.ac.in/~amit/">Amit Hogadi</a>.
  username: shambhavopaya
  email: ndeshmukh[at]impan[dot]pl
  avatar: /assets/img/Me.jpg

# Url settings
url: "https://shambhavopaya.github.io"
baseurl:
permalink: /:title/
google_analytics: G-D3HYE4D5PZ
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
